services:
  snapserver:
    image: ghcr.io/sweisgerber/snapcast:latest
    environment:
      - PUID=1000
      - PGID=1000 # set to audio group ID
      - TZ=Europe/Zurich
    networks:
      snapcast-ipvlan:
        ipv4_address: 192.168.0.20
    volumes:
      - snapcast-fifos:/audio/
      - ./snapserver.conf/:/config/snapserver.conf:ro
      - snapcast-data:/data/

  mopidy:
    image: ghcr.io/sweisgerber/mopidy:latest
    environment:
      - PUID=1000 # user ID which the mopidy service will run as, needs permissions to access the music
      - PGID=1000 # group ID which the mopidy service will run as, needs permissions to access the music
      - TZ=Europe/Zurich
      # - DOCKER_MODS=linuxserver/mods:universal-package-install
      # - INSTALL_PIP_PACKAGES=Mopidy-TuneIn
      # - INSTALL_PACKAGES=gst-plugins-bad
    ports:
      - 6600:6600/tcp # MPD port
      - 6680:6680/tcp # Mopidy Web Interface
    networks:
      - sound-server
    healthcheck:
      test: curl -f http://localhost:6680/iris/http/get_config || exit 1
      timeout: 5s
      retries: 5
    volumes:
      - iris-data:/data/ # Iris-specific storage
      - ./mopidy.conf:/config/mopidy.conf:ro
      - /srv/nc-data-no-bkp/Music:/music/:ro
      - snapcast-fifos:/tmp/snapcast-fifos

networks:
  sound-server:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: sound-server
    name: sound-server
  snapcast-ipvlan:
    driver: ipvlan
    driver_opts:
      parent: enp0s31f6
      # to enable mDNS (which advertises the Spotify Connect service), the container must receive Multicast packets
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1

volumes:
  snapcast-fifos:
  snapcast-data:
  iris-data: