services:
snapserver:
    image: 'ghcr.io/firefrei/snapcast/server:latest'
    restart: always
    #cap_add:
      #- NET_BIND_SERVICE   # Optional: allow container to bind privileged ports (>1024)
    environment:
      # See README.md for all environment options.
      TZ: Europe/Zurich
      # NGINX_ENABLED: "1"  # enable NGINX for HTTPS -> requires to bind to port 443 by default
      #NGINX_HTTPS_PORT: "4433"  # use port 4433 instead of 4433
    volumes:
      # Snapcast: Configuration and run-time data
      - snapcast-data:/app/data/
      #- snapcast-config:/app/config/
      #- ./config_snapcast/:/app/config/

      # NGINX: HTTPS certificates
      # nginx-certs:/app/certs/
      #- ./nginx_certs/:/app/certs/


    # Network Alternative 1: Bridge container directly into your home network
    #networks:
      #bridged-home-network:
        #ipv4_address: <desired-ip-of-container>

    # Network Alternative 2: Use port-forwarding of host ports
    networks:
      - sound-server
    ports:
      # Snapcast Ports
      - '1704-1705:1704-1705'
      - '1780:1780'
      # AirPlay ports
      - '3689:3689'
      - '5000:5000'
      - '6000-6009:6000-6009/udp'
      # AirPlay-2 ports
      #- '319-320:319-320/udp'
      #- '3689:3689'
      #- '5000:5000'
      #- '7000:7000'
      #- '6000-6009:6000-6009/udp'
      # Avahi ports
      - '5353:5353'
      # NGINX ports
      # - '443:443'
  mopidy:
    image: jaedb/iris
    environment:
      PIP_PACKAGES: #Mopidy-YTMusic Mopidy-Tidal Mopidy-SoundCloud Mopidy-MusicBox-Webclient
    ports:
      - 6600:6600/tcp # MPD port
      - 6680:6680/tcp # Mopidy Web Interface
    networks:
      - sound-server
    healthcheck:
      test: curl -f http://localhost:6680/iris/http/get_config || exit 1
      timeout: 5s
      retries: 5
    volumes:
      # - ./mopidy/iris:/iris/mopidy/iris # To use a locally-built UI 
      - /var/lib/mopidy/iris:/var/lib/mopidy/iris # Iris-specific storage
      - /var/lib/mopidy/m3u:/var/lib/mopidy/m3u # To persist local playlists
      - /etc/sound-server/mopidy.conf:/config/mopidy.conf:ro
      - /srv/nc-data-no-bkp/Music:/var/lib/mopidy/media:ro
      - /tmp/sound-server:/tmp
volumes:
  #snapcast-config:
  snapcast-data:
  nginx-certs:

networks:
  sound-server:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: sound-server
    name: sound-server