# available keycodes can be found in /usr/include/linux/input-event-codes.h
[[protocols]]
name = "HK970"
protocol = "nec"
variant = "necx"
[protocols.scancodes]
0x8070C0 = "KEY_POWER" # ON
0x80709F = "KEY_SLEEP" # OFF
0x8070C7 = "KEY_VOLUMEUP"
0x8070C8 = "KEY_VOLUMEDOWN"
0x807002 = "KEY_PLAYPAUSE"
0x807009 = "KEY_10CHANNELSDOWN"
0x807008 = "KEY_10CHANNELSUP"
0x8070C4 = "KEY_CD"
0x8070C3 = "KEY_TUNER"
0x8070C2 = "KEY_PLAYER" # PHONO
0x8070D3 = "KEY_TV"
0x8070CC = "KEY_TAPE"
0x8070C5 = "KEY_AUX"
0x8070D5 = "KEY_DVD" # CDR
# 0x80701E = "KEY_FOLDERPLUS"
# 0x80701F = "KEY_FOLDERMINUS"
0x8070DE = "KEY_MODE"
0x807005 = "KEY_PREVIOUS"
0x807004 = "KEY_NEXT"
0x807007 = "KEY_REWIND"
0x807001 = "KEY_STOP"
0x807006 = "KEY_FORWARD"
0x807000 = "KEY_EJECTCLOSECD"
0x80700A = "KEY_MEDIA_REPEAT"
0x80704D = "KEY_SHUFFLE"
0x807084 = "KEY_SCROLLUP"
0x807085 = "KEY_SCROLLDOWN"
0x8070C1 = "KEY_MUTE"
0x8070A8 = "KEY_SELECT"
# 0x807081 = "KEY_BAND"
# 0x8272DD = "KEY_RDS"
# 0x807093 = "KEY_FMMODE"
# 0x807091 = "KEY_AUTO"
0x80701A = "KEY_0"
0x807011 = "KEY_1"
0x807012 = "KEY_2"
0x807013 = "KEY_3"
0x807014 = "KEY_4"
0x807015 = "KEY_5"
0x807016 = "KEY_6"
0x807017 = "KEY_7"
0x807018 = "KEY_8"
0x807019 = "KEY_9"
